"""Adiciona coluna link_imagem nas tabelas Projeto e Noticia

Revision ID: 022da2dada1d
Revises: 4df82d616b83
Create Date: 2024-12-08 12:59:23.720461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022da2dada1d'
down_revision = '4df82d616b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_imagem', sa.String(length=255), nullable=True))

    with op.batch_alter_table('Projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_imagem', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projeto', schema=None) as batch_op:
        batch_op.drop_column('link_imagem')

    with op.batch_alter_table('Noticia', schema=None) as batch_op:
        batch_op.drop_column('link_imagem')

    # ### end Alembic commands ###
