"""ReAumentando tamanho do atributo Senha para o ADM

Revision ID: 3a9d597e13d6
Revises: e1585cfff8b5
Create Date: 2024-11-22 16:24:30.896343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a9d597e13d6'
down_revision = 'e1585cfff8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Administrador', schema=None) as batch_op:
        batch_op.alter_column('Senha',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Administrador', schema=None) as batch_op:
        batch_op.alter_column('Senha',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    # ### end Alembic commands ###
