"""Removendo 'NotNull' do atributo IdProjeto na tabela Anima
l 

Revision ID: 4df82d616b83
Revises: 7c942b739e63
Create Date: 2024-11-23 18:22:27.941366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4df82d616b83'
down_revision = '7c942b739e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animal', schema=None) as batch_op:
        batch_op.alter_column('IdProjeto',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Animal', schema=None) as batch_op:
        batch_op.alter_column('IdProjeto',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
