"""Reaumentando tamanho do atributo Senha para o ADM

Revision ID: 7c942b739e63
Revises: 3a9d597e13d6
Create Date: 2024-11-22 16:54:47.142646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c942b739e63'
down_revision = '3a9d597e13d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Administrador', schema=None) as batch_op:
        batch_op.alter_column('Senha',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Administrador', schema=None) as batch_op:
        batch_op.alter_column('Senha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
